/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */
plugins{
    base
}
dependencies {
    default(project(mapOf(
        "path" to ":subprj",
        "configuration" to "mep_py"
        )
    ))
}

abstract class Consumer : DefaultTask() {
    @get:InputFiles
    abstract val inputFiles: ConfigurableFileCollection 

    @TaskAction
    fun consume() {
        val input: File = inputFiles.getSingleFile()
        println(input)
        val message = input.readText()
        logger.quiet("Read '${message}' from ${input}")
    }
}

tasks.register<Consumer>("c1"){
    inputFiles.from(configurations.default)
    // println("I'm build")
}