/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */

buildDir = file("pythonDAGoutput")

abstract class Producer: DefaultTask(){
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun produce(){
        val message = "Hello World!"
        val output = outputFile.get().asFile
        output.writeText(message)
        logger.quiet("Wrote ${message} to ${output}")
    }
}

val task1 = tasks.register<Producer>("task1"){
    outputFile.set(layout.buildDirectory.file("file.txt"))
}


val mep_py by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
}


artifacts {
    add("mep_py", task1.get().outputFile){
        builtBy(task1)
    }
}

